### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by Arcmoon-Hu** [Apm5/ImageNet_ResNet_Tensorflow2.0#2]
测试的时候，使用model.predict时就不用管BN training是否False了吧？

**Comment by Apm5** [comment]
@qiezikuangge 
是需要的，true会导致测试过程BN里的两个统计参数发生变化

**Comment by Arcmoon-Hu** [comment]
"3) When performing inference using a model containing batch normalization, it
is generally (though not always) desirable to use accumulated statistics
rather than mini-batch statistics. This is accomplished by passing
`training=False` when calling the model, or using `model.predict`."
去找了一下layers.BN的帮助文档，应该是当使用.predict的时候不用管training了

**Comment by Apm5** [comment]
@qiezikuangge 
我也确认了一下，如果你是说使用原版的self.predict方法，确实不用管bn的问题。
但是我这个项目中没有用这个方法，所以还是需要注意bn的问题的
